//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMonitoring_fw
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDonnee
    {
        public int id { get; set; }
        public int idProjet { get; set; }
        public string host { get; set; }
        public string databaseName { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public string cheminSauvegarde { get; set; }
        public string libelle { get; set; }
    }
}
