//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMonitoring_fw.BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaseDonnee> BaseDonnee { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Projet> Projet { get; set; }
        public DbSet<Serveur> Serveur { get; set; }
        public DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
