//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMonitoring_fw.BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaseDonnee> BaseDonnee { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Serveur> Serveur { get; set; }
        public DbSet<Utilisateur> Utilisateur { get; set; }
        public DbSet<EnumTheme> EnumTheme { get; set; }
        public DbSet<Projet> Projet { get; set; }
        public DbSet<EnumTypeFavoris> EnumTypeFavoris { get; set; }
        public DbSet<UtilisateurFavoris> UtilisateurFavoris { get; set; }
    }
}
