//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMonitoring_fw
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public int id { get; set; }
        public string libelle { get; set; }
        public int idTheme { get; set; }
        public string urlProd { get; set; }
        public string urlTest { get; set; }
    }
}
