//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMonitoring_fw
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public int id { get; set; }
        public string libelle { get; set; }
        public int idTheme { get; set; }
        public string urlProd { get; set; }
        public string urlTest { get; set; }
    }
}
