//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMonitoring_fw
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilisateurFavoris
    {
        public int idUtilisateur { get; set; }
        public int idEntite { get; set; }
        public int idType { get; set; }
    }
}
